name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build and Test (Release Asserts)
    runs-on: ubuntu-20.04
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Checkout project
      uses: actions/checkout@v2
      with:
        path: sandbox
    - name: Checkout IREE
      uses: actions/checkout@v2
      with:
        path: iree
        repository: google/iree

    # Note that actions/checkout is faster than a general purpose submodule
    # fetch (by a lot), so we get the commit hash and check it out ourselves.
    - name: Get LLVM Commit Hash
      id: get_llvm_commit_hash
      run: echo "LLVM_COMMIT=$(cat ${GITHUB_WORKSPACE}/sandbox/pinned-llvm-version)" >> $GITHUB_ENV
    - name: Checkout llvm-project
      uses: actions/checkout@v2
      with:
        path: llvm-project
        repository: llvm/llvm-project
        ref: ${{ env.LLVM_COMMIT }}
        

    - name: Install Python depends
      run: |
        python -m pip install -r ${GITHUB_WORKSPACE}/sandbox/requirements.txt
    - name: Install Ninja
      uses: llvm/actions/install-ninja@55d844821959226fab4911f96f37071c1d4c3268
    - name: Ccache for C++ compilation
      uses: hendrikmuhs/ccache-action@4687d037e4d7cf725512d9b819137a3af34d39b3
      with:
        key: ${{ runner.os }}-buildtestasserts
        # LLVM needs serious cache size
        max-size: 6G

    - name: Build
      run: |
        cd ${GITHUB_WORKSPACE}/sandbox
        python configure.py --llvm-path=../llvm-project
        ccache -s
        echo "IREE_LLVM_SANDBOX_BUILD_DIR=${GITHUB_WORKSPACE}/sandbox/build" >> $GITHUB_ENV

    - name: Test
      run: |
        cd ${GITHUB_WORKSPACE}/sandbox
        python run_tests.py

    # TODO: Add a build for IREE but it will get stale as soon as we update core + sandbox
