name: Database Iterators Standalone

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-20.04
    env:
      LLVM_SYMBOLIZER_PATH: /usr/lib/llvm-11/bin/llvm-symbolizer
    steps:
    - name: Set up Python
      uses: actions/setup-python@13ae5bb136fac2878aff31522b9efb785519f984 # v4.3.0
      with:
        python-version: 3.9

    - name: Checkout project
      uses: actions/checkout@v3
      with:
        path: sandbox

    - name: Install Ninja
      uses: lukka/get-cmake@latest

    - name: Install doxygen
      run: |
        sudo apt-get install -y doxygen graphviz

    - name: Define build dir
      run: |
        echo "DATABASE_ITERATORS_STANDALONE_BUILD_DIR=${GITHUB_WORKSPACE}/sandbox/experimental/iterators/examples/database-iterators-standalone/build" >> $GITHUB_ENV

    - name: Setup CMake
      run: |
        mkdir ${DATABASE_ITERATORS_STANDALONE_BUILD_DIR}
        cd ${DATABASE_ITERATORS_STANDALONE_BUILD_DIR}
        cmake -G Ninja ..

    - name: Build
      run: |
        cd ${DATABASE_ITERATORS_STANDALONE_BUILD_DIR}
        ninja
        ninja DatabaseIteratorsDocs

    - name: Test
      run: |
        cd ${DATABASE_ITERATORS_STANDALONE_BUILD_DIR}
        ninja test
